name: Python CI

on:
  push:
    branches:
      - main
      - "python**"
  pull_request:
    branches:
      - main
      - "python**"

jobs:
  test_python:
    runs-on: ubuntu-latest
    name: Test Python
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/
